# Import Libraries needed by this notebook

In [3]:
import numpy as np
import torch
import tensorflow as tf

# Scalars (Rank 0 Tensors) in Base Python

In [1]:
x = 25

x

25

In [5]:
type(x)

int

In [4]:
y = 3

y

3

In [6]:
pysum = x + y

pysum

28

In [7]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [8]:
type(float_sum)

float

# Scalars in PyTorch

In [21]:
import torch

In [10]:
x_pt = torch.tensor(25)

x_pt

tensor(25)

In [12]:
x_pt.shape

torch.Size([])

# Scalars in Tensorflow

In [26]:
import tensorflow as tf

In [14]:
x_tf = tf.Variable(25, dtype=tf.int16)

x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [15]:
x_tf.shape

TensorShape([])

In [16]:
y_tf = tf.Variable(50, dtype=tf.int16)

In [17]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=75>

In [20]:
tf_sum = tf.add(x_tf, y_tf)

In [19]:
x_tf.shape

TensorShape([])

In [21]:
tf_sum.numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(), dtype=int16, numpy=75>>

# Vectors (Ranks 1 Tensors) in NumPy

In [3]:
import numpy as np

In [3]:
x = np.array([25, 2, 5])

In [25]:
len(x)

3

In [26]:
x.shape

(3,)

In [27]:
x[0]

25

In [28]:
type(x[0])

numpy.int64

# Vector Transposition

In [32]:
x = np.array([[25,2,5]])

In [37]:
x

array([[25,  2,  5]])

In [33]:
x_t = x.T

In [36]:
x_t

array([[25],
       [ 2],
       [ 5]])

In [34]:
x_t.shape

(3, 1)

# Zero Vectors

Has no effect if added to another vector

In [38]:
z = np.zeros(3)

z

array([0., 0., 0.])

# Vectors in PyTorch and TensorFlow

In [41]:
x_pt = torch.tensor([25, 2, 5])

x_pt

tensor([25,  2,  5])

In [43]:
x_tf = tf.Variable([25, 2, 5])

x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

# L^2 Norm

In [44]:
x

array([[25,  2,  5]])

In [52]:
(25**2 + 2**2 + 5**2) ** (1/2)

25.573423705088842

In [45]:
np.linalg.norm(x)

25.573423705088842

# L^1 Norm

In [53]:
x

array([[25,  2,  5]])

In [54]:
np.abs(25) + np.abs(2) + np.abs(5)

32

# Squared L^2 Norm

In [4]:
x

array([25,  2,  5])

In [5]:
(25**2 + 2**2 + 5**2)

654

In [9]:
np.dot(x, x)

654

# Max Norm

In [10]:
x

array([25,  2,  5])

In [12]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

# Orthogonal Vectors

In [5]:
i = np.array([1, 0])

In [6]:
j = np.array([0, 1])

In [7]:
np.dot(i, j)

0

# Metrices (Rank 2 Tensors) in NumPy

In [4]:
X = np.array([[25, 2],[5, 26],[3, 7]])

X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [14]:
X.shape

(3, 2)

In [15]:
X.size

6

In [17]:
X[:, 0]

array([25,  5,  3])

In [19]:
X[1, :]

array([ 5, 26])

In [20]:
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

# Metrices in PyTorch

In [14]:
X_pt = torch.tensor([[25, 2],[5, 26],[3, 7]])

X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [28]:
X_pt.shape

torch.Size([3, 2])

In [29]:
X_pt[1, :]

tensor([ 5, 26])

# Metrices in Tensorflow

In [9]:
X_tf = tf.Variable([[25, 2],[5, 26],[3, 7]])

X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [31]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [32]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

# Higher Rank Tensors

As an example, rank 4 tensors are common for images, where each dimension correponds to:


1.   Number of images in training batch, e.g.: 32
2.   Image height in pixels
3.   Image width in pxels
4.   Number of color channels



In [ ]:
images_pt = torch.zeros([32, 28, 28, 3])

images_pt

In [ ]:
images_tf = tf.zeros([32, 28, 28, 3])

images_tf

# Tensor Transposition

In [5]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [6]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [8]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [10]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

# Basic Arithmatical Properties

Applying or multiplying with scalar applies operation to all elements and tensor shape is retained

In [11]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [12]:
X * 2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [13]:
X + 2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [15]:
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [16]:
X_pt * 2 + 2

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [17]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [18]:
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [19]:
tf.add(tf.multiply(X_tf, 2),2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

If two tensors have the same size, operations are often by default applied element-wise. This is not matrix multiplication, which we'll cover later, but is rather called the **Hadamard product** or simply the **element-wise** product.

In [20]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [22]:
A = X + 2

A

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [23]:
A + X

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [24]:
A * X

array([[675,   8],
       [ 35, 728],
       [ 15,  63]])

In [25]:
A_pt = X_pt + 2

In [26]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [27]:
A_pt + X_pt

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [28]:
A_pt * X_pt

tensor([[675,   8],
        [ 35, 728],
        [ 15,  63]])

In [29]:
A_tf = X_tf + 2

In [30]:
A_tf + X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [31]:
A_tf * X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[675,   8],
       [ 35, 728],
       [ 15,  63]], dtype=int32)>

# Reduction

In [32]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [34]:
X.sum()

68

In [35]:
torch.sum(X_pt)

tensor(68)

In [36]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=68>

Summing all rows

In [37]:
X.sum(axis=0)

array([33, 35])

Summing all columns

In [39]:
X.sum(axis=1)

array([27, 31, 10])

In [40]:
torch.sum(X_pt, 0)

tensor([33, 35])

In [41]:
torch.sum(X_pt, 0)

tensor([33, 35])

In [42]:
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([33, 35], dtype=int32)>

# Dot Product

In [46]:
x = np.array([25, 2, 5])

x

array([25,  2,  5])

In [47]:
y = np.array([0, 1, 2])

y

array([0, 1, 2])

In [48]:
25 * 0 + 2 * 1 + 5 * 2

12

In [49]:
np.dot(x, y)

12

Use PyTorch

In [51]:
x = torch.tensor([25, 2, 5])

x

tensor([25,  2,  5])

In [52]:
y = torch.tensor([0, 1, 2])

y

tensor([0, 1, 2])

In [54]:
np.dot(x, y)

12

In [55]:
torch.dot(x, y)

tensor(12)

# Matrix Multiplication (with a Vector)

In [ ]:
A = np.array([[3, 4], [5, 6], [7, 8]])

A

In [4]:
b = np.array([1, 2])

b

array([1, 2])

In [5]:
np.dot(A, b)

array([11, 17, 23])

In [6]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])

A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [7]:
b_pt = torch.tensor([1, 2])

b_pt

tensor([1, 2])

In [8]:
torch.matmul(A_pt, b_pt)

tensor([11, 17, 23])

In [14]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])

A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [15]:
b_tf = tf.Variable([1, 2])

b_tf

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [18]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

# Metrix Multiplication (with Two Metrices)

In [4]:
A = np.array([[3, 4], [5, 6], [7, 8]])

A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [6]:
B = np.array([[1, 9], [2, 0]])

B

array([[1, 9],
       [2, 0]])

In [7]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

**Note that matrix multiplication is not commutative.**

In [9]:
A_pt = torch.tensor([[3, 4], [5, 6], [7, 8]])

A_pt

tensor([[3, 4],
        [5, 6],
        [7, 8]])

In [10]:
B_pt = torch.from_numpy(B)

B_pt

tensor([[1, 9],
        [2, 0]])

In [11]:
torch.matmul(A_pt, B_pt)

tensor([[11, 27],
        [17, 45],
        [23, 63]])

In [14]:
A_tf = tf.Variable([[3, 4], [5, 6], [7, 8]])

A_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [15]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)

B_tf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 9],
       [2, 0]], dtype=int32)>

In [16]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 27],
       [17, 45],
       [23, 63]], dtype=int32)>

# Symmetric Metrices

In [17]:
A_sym = np.array([[0, 1, 2], [1, 7, 8],[2, 8, 9]])

A_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [18]:
B_sym = A_sym.T

B_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [19]:
A_sym == B_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

# Identity Metrices

In [20]:
I = torch.tensor([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [21]:
x_pt = torch.tensor([[10, 20, 30]])

x_pt

tensor([[10, 20, 30]])

In [22]:
torch.matmul(x_pt, I)

tensor([[10, 20, 30]])

In [28]:
X_pt = torch.tensor([[12,13, 14], [4, 5, 6]])

X_pt

tensor([[12, 13, 14],
        [ 4,  5,  6]])

In [29]:
torch.matmul(X_pt, I)

tensor([[12, 13, 14],
        [ 4,  5,  6]])

# The Frobenius Norm

In [30]:
X = np.array([[1, 2], [3, 4]])

X

array([[1, 2],
       [3, 4]])

In [33]:
norm = (1**2 + 2**2 + 3**2 + 4**2) ** (1/2)

norm

5.477225575051661

In [32]:
norm_np = np.linalg.norm(X)

norm_np

5.477225575051661

In [36]:
X_pt = torch.tensor([[1, 2], [3, 4.]])

X_pt

tensor([[1., 2.],
        [3., 4.]])

In [37]:
torch.norm(X_pt)

tensor(5.4772)

In [40]:
X_tf = tf.Variable([[1, 2], [3, 4.]])

X_tf



<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [41]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=5.4772257804870605>

# Matrix Inversion

In [49]:
X = np.array([[4, 2], [-5, -3]])

X

array([[ 4,  2],
       [-5, -3]])

In [50]:
Xinv = np.linalg.inv(X)

Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [51]:
y = np.array([4, -7])

y

array([ 4, -7])

In [53]:
w = np.dot(Xinv, y)

w

array([-1.,  4.])

In [56]:
torch.inverse(torch.Tensor([[4, 2], [-5, -3.]]))

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

In [57]:
tf.linalg.inv(tf.Variable([[4, 2], [-5, -3.]]))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>

# Matrix Inversion where no Soltion

In [4]:
x = np.array([[1, 2], [2, 4]])

x

array([[1, 2],
       [2, 4]])

In [5]:
np.linalg.inv(x)

LinAlgError: Singular matrix

# The Trace Operator

In [7]:
A = np.array([[25, 2], [5, 4]])

A

array([[25,  2],
       [ 5,  4]])

In [8]:
25 + 4

29

In [9]:
np.trace(A)

29