# NumPy for Numerical Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
import bokeh
import plotly
import folium

# Arithmetic Functions

In [6]:
print("-------------A--------------")
A = np.arange(10)
print(A)
print(A.shape)
print("-------------A after adding axis--------------")
C = A[np.newaxis,:]
print(C)
print(C.shape)
print("-------------B--------------")
B = np.random.randint(0,10, (1,10))
print(B)
print(B.shape)

-------------A--------------
[0 1 2 3 4 5 6 7 8 9]
(10,)
-------------A after adding axis--------------
[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)
-------------B--------------
[[8 0 5 6 7 3 2 3 7 5]]
(1, 10)


#### Add Arrays

In [10]:
D = A + C
print(D)
print(D.shape)
E = np.add(A, C)
print(E)
print(E.shape)

[[ 0  2  4  6  8 10 12 14 16 18]]
(1, 10)
[[ 0  2  4  6  8 10 12 14 16 18]]
(1, 10)


#### Squeeze additional dimensions

In [9]:
E = D.squeeze()
print(E)
print(E.shape)

[ 0  2  4  6  8 10 12 14 16 18]
(10,)


#### Sum all the values

In [ ]:
from numpy._core.multiarray import arange
a_sum = np.sum(D)
print(a_sum)
print("-------------In below, axis-0 is 2, axis-1 is 2, axis-2 is 5 and axis-3 is 4--------------")
n_array = np.arange(80).reshape(2, 2, 5, 4)
print(n_array)
print(n_array.shape)
print("-----------Sum by axis = 0 ------")
sum_array = n_array.sum(axis=0)
print(sum_array)
print(sum_array.shape)

#### Trigonometric Functons