In [7]:
import torch
import numpy as np

In [3]:
x = 25

type(x)

int

In [6]:
scalar_tensor = torch.tensor(25)
print(scalar_tensor)
print(scalar_tensor.shape)

tensor(25)
torch.Size([])


# Vector and Transpose

In [18]:
x = np.array([[25, 2, 5]])

print(x)

print(x.shape)

print(type(x))

x = x.T

print(x)

print(x.shape)

print(type(x))

print('-------------------------------')

x = torch.tensor([25, 2, 5])
print(x)




[[25  2  5]]
(1, 3)
<class 'numpy.ndarray'>
[[25]
 [ 2]
 [ 5]]
(3, 1)
<class 'numpy.ndarray'>
-------------------------------
tensor([25,  2,  5])


# Zeors Vectors

In [14]:
z = np.zeros(3)

print(z)

print(z.shape)

print(type(z))

[0. 0. 0.]
(3,)
<class 'numpy.ndarray'>


# L<sup>2</sup> Norm

In [19]:
x = np.array([25, 2, 5])

np.linalg.norm(x)

np.float64(25.573423705088842)

# Matrices in PyTorch

In [ ]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])

print(X_pt)

print(X_pt.shape)

print(X_pt[1,:])

print(X_pt[:,0])

print(X_pt.T)

print(X_pt * 2)

print(X_pt * 2 + 3)

print(torch.add(torch.multiply(X_pt, 2), 3))

Y_pt = X_pt + 2

print(Y_pt + X_pt)

print(Y_pt * X_pt)



# Dot Product

In [33]:
X_pt = torch.tensor([25, 2., 7])
Y_pt = X_pt + 2

torch.dot(X_pt, Y_pt)

tensor(746.)

# Matrix Multiplication